# Generated by Django 2.2 on 2019-04-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lovername', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=15)),
                ('phnum', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('firstname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('about', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('phnum', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('confpass', models.CharField(max_length=15)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
    ]
